export type AppView =
  | 'produtos'
  | 'produtosFamilia'
  | 'produtosGrupos'
  | 'produtosImportacao'
  | 'produtosSubGrupos'
  | 'temperatura'
  | 'ocupacao'
  | 'seguranca'
  | 'enderecamento'
  | 'inventarios'
  | 'inventarioCaptura'
  | 'contagem'
  | 'contagemCaptura'
  | 'estoque'
  | 'painel'
  | 'permissoes'
